### ISSUE TITLE
dv*.jars are not created

### ISSUE THREAD

**Issue by fatihersinadim** [spoofzu/DeepViolet#230]
Hi @spoofzu I still have the same issue #19 

I built DeepViolet with "mvn clean install", but the dv*.jars are not created.

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T18:41:47+02:00)
Java version: 1.8.0_73, vendor: Oracle Corporation
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.3", arch: "x86_64", family: "mac"

**Comment by kingthorin** [comment]
According to the releases on github something changed Dec 17: Beta 4 was released with a jar then nothing between 1.0.10 and 1.0.38 on Dec 21 (the most recent "release") have a jar.

**Comment by spoofzu** [comment]
I changed the scripts around Nov/Dec 2017 in an attempt to get publishing to mavencentral working.  For now, you can build the API jar locally.  mvn clean | mvn install, then check your target folder for the jar and rename as you wish (dvAPI.jar).  I working on getting some assistance for the mavencentral publishing.  Note: moving forward this jar only contains the API.  In the next day or or two I am creating another repo to hold the tools/reference cases.  There were some requests to remove the reference tools from the API jar.  That's my plan.  btw - I cleaned up beta 5 so the latest release should reflect beta 5 and is available for you to try.

**Comment by kingthorin** [comment]
Great

**Comment by spoofzu** [comment]
Instructions how to build on your computer using Maven are on, https://github.com/spoofzu/DeepViolet/wiki/Build-on-Your-Computer.  ZAP team confirm build instructions working for them.  Closing this issue.
