### ISSUE TITLE
Usage of getDefaultPort prevents SSL/TLS connections to other ports

### ISSUE THREAD

**Issue by vladidx** [spoofzu/DeepViolet#292]
https://github.com/spoofzu/DeepViolet/blob/36c3909c5ae24acdc4d494aad5e48a1f7c3c6074/src/main/java/com/mps/deepviolet/api/DVFactory.java#L62

By making use of getDefaultPort() during the socket creation, there is no chance to connect to servers which run on ports other than 443. It would make more sense to use this as a fallback if getPort() doesn't return a proper value.

**Comment by spoofzu** [comment]
Agreed, thanks.  Looks like it should be url.getPort().  Silly mistake.  Not surprised it evaded my minimalist unit tests.  I will improve the unit tests as well.  If you want this fixed asap send me a PR and I will approve it.  Otherwise it may be a few days before I get to it.

**Comment by spoofzu** [comment]
Merged, thanks.
