### ISSUE TITLE
Inform OWASP this project is abandon?

### ISSUE THREAD

**Issue by kingthorin** [spoofzu/DeepViolet#332]
> THIS PROJECT IS NOT BEING ACTIVELY MAINTAINED. I DON'T RECOMMEND THE IT BE USED FOR ANYTHING IMPORTANT; HOWEVER, IT REMAINS AVAIABLE FOR ARCHIVAL PURPOSES. THIS PROJECT WAS A FUN EXPERIMENT AND IT WAS EXCITING TO SHARE IT WITH EVERYONE. AT THIS TIME, I'M PLACING MY TIME AND ENERGY INTO OTHER AREAS. JUN 27, 2019 --MILTON

@spoofzu You should probably inform OWASP that this is no longer a project and that it doesn't need a site etc on the organization's site.

https://owasp.org/www-project-deepviolet-tls-ssl-scanner/

**Comment by spoofzu** [comment]
Interesting timing,  my availability for projects is improving.  I've been exploring the idea of moving forward on this project again.  I'm considering some new features like, rewriting parts of the core, TLS 1.3 support, maybe CT support, etc.  Let me know if this would be of interest to the ZAP project.
