### ISSUE TITLE
Provide only documentation

### ISSUE THREAD

**Issue by edermi** [spoofzu/DeepViolet#9]
I was not able to find a link to browse documentation online.
If there's a lack of resources for this, I'd suggest to use [Github pages to host JavaDoc](http://stackoverflow.com/questions/3939595/making-javadocs-available-with-github-sonatype-maven-repo). See [here](https://help.github.com/articles/user-organization-and-project-pages/) for further information on Github pages

**Comment by spoofzu** [comment]
Good point.  I need do the documentation differently.  For now the documentation sources are the: main project github page, javadocs located in the doc folder (click on the index.html on your hard drive), another source is the OWASP project landing page,
[OWASP DeepViolet TLS/SSL Scanner](https://www.owasp.org/index.php/OWASP_DeepViolet_TLS/SSL_Scanner)

I admit the documentation is not the best.  I will add this to my list as well and leave this issue open for now for tracking.

**Comment by spoofzu** [comment]
Setup up github hosted javadocs.  Added a link on Readme.md and the project wiki.  Thanks for the tip.  [API JavaDocs](https://spoofzu.github.io/DeepViolet/)
